apiVersion: 1

datasources:
  - name: Pipeline PostgreSQL
    type: postgres
    uid: pipeline-pg
    url: postgres:5432
    user: pipeline
    secureJsonData:
      password: pipeline
    jsonData:
      database: pipeline
      sslmode: disable
      maxOpenConns: 10
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1500
      timescaledb: false
    isDefault: true
    editable: false
